refactor: Reformat code

diff --git a/git_hooks/pre-commit b/git_hooks/pre-commit
--- a/git_hooks/pre-commit
+++ b/git_hooks/pre-commit
@@ -1,22 +1,29 @@
-#!/usr/bin/sh
+#!/usr/bin/
+sh
 #
+
 # An example hook script to verify what is about to be committed.
 # Called by "git commit" with no arguments.  The hook should
 # exit with non-zero status after issuing an appropriate message if
 # it wants to stop the commit.
 #
+
 # To enable this hook, rename this file to "pre-commit".
 
 # Run tests, quiet mode, color on.
-cargo test --color always || {
-    echo;
-    echo "============================================================"
-    echo "|   Some tests FAILED: please fix them before committing   |"
-    echo "============================================================"
-    exit 1;
+        cargo
+test --
+color always
+|| {
+echo;
+echo "============================================================"
+echo "|   Some tests FAILED: please fix them before committing   |"
+echo "============================================================"
+exit 1;
 }
 
 echo "your mom"
 
 # Reformat code
-cargo fmt --quiet
+cargo fmt
+--quiet
